insert into Jogos (nome,preco) values('League of Legends',0.00);
insert into Jogos (nome,preco) values('Paladins',0.00);
insert into Jogos (nome,preco) values('PUBG',55.99);
insert into Jogos (nome,preco) values('CS GO',24.99);
insert into Jogos (nome,preco) values('Rainbow Six Siege',49.99);
insert into Jogos (nome,preco) values('ARK',105.99);
insert into Jogos (nome,preco) values('Path of Exile',0.00);
insert into Jogos (nome,preco) values('GTA V',99.99);
insert into Jogos (nome,preco) values('Dont Starve Together',27.99);
insert into Jogos (nome,preco) values('Arma 3',119.99);
insert into Biblioteca (jogo) values(1);
insert into Biblioteca (jogo) values(2);
insert into Biblioteca (jogo) values(3);
insert into User (u,nome,codigo) values(2,'user2',1);
insert into User (u,nome,codigo) values(2,'user2',2);
insert into User (u,nome,codigo) values(2,'user2',7);
insert into User (u,nome,codigo) values(2,'user2',9);
insert into User (u,nome,codigo) values(3,'user3',1);
insert into User (u,nome,codigo) values(3,'user3',2);
insert into User (u,nome,codigo) values(3,'user3',5);
insert into User (u,nome,codigo) values(3,'user3',6);
insert into User (u,nome,codigo) values(3,'user3',7);
insert into User (u,nome,codigo) values(3,'user3',8);
insert into User (u,nome,codigo) values(3,'user3',9);
insert into User (u,nome,codigo) values(3,'user3',10);
insert into User (u,nome,codigo) values(4,'user4',2);
insert into User (u,nome,codigo) values(4,'user4',3);
insert into User (u,nome,codigo) values(4,'user4',4);
insert into User (u,nome,codigo) values(4,'user4',5);
insert into User (u,nome,codigo) values(5,'user5',3);
insert into User (u,nome,codigo) values(5,'user5',10);
insert into User (u,nome,codigo) values(6,'user6',1);
insert into User (u,nome,codigo) values(7,'user7',4);
insert into User (u,nome,codigo) values(7,'user7',5);
insert into User (u,nome,codigo) values(7,'user7',8);
insert into User (u,nome,codigo) values(7,'user7',10);
insert into User (u,nome,codigo) values(8,'user8',2);
insert into User (u,nome,codigo) values(9,'user9',6);
insert into User (u,nome,codigo) values(9,'user9',8);
insert into User (u,nome,codigo) values(9,'user9',9);